### ISSUE TITLE
Add pressed state

### ISSUE THREAD

**Issue by dchest** [sapegin/social-likes#38]
It would be nice to have a style for "pressed" state.

Here's what I came up with:

![pressed](https://f.cloud.github.com/assets/52677/1297647/852e9722-30e6-11e3-9623-a8b1859e4d80.gif)

CSS:

``` css
.social-likes__button:active {
  -webkit-box-shadow: inset 0 0 3px rgba(0, 0, 0, 0.3));
          box-shadow: inset 0 0 3px rgba(0, 0, 0, 0.3));
}
```
